apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infrabin.fullname" . }}
  labels:
    app: {{ include "infrabin.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "infrabin.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "infrabin.name" . }}
      {{- if .Values.istio.enabled }}
      annotations:
        {{- range $k,$v := .Values.istio.sidecarAnnotations }}
        {{ $k }}: "{{ $v }}"
        {{- end }}
      {{- end }}
    spec:
      containers:
        - name: infrabin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
