{{- if and .Values.istio.enabled .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "infrabin.fullname" . }}-vs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - {{ include "infrabin.fullname" . }}-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /grafana
      route:
        - destination:
            host: {{ .Values.istio.grafanaHost | default "kube-prometheus-stack-grafana.monitoring.svc.cluster.local" }}
            port:
              number: {{ .Values.istio.grafanaPort | default 80 }}
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
